**General purpose array processing package, provides high performance multi-dimensional array object. numpy is memory effcient / faster compared to array and also expands to N dimensional (2D / 3D).**

In [2]:
import numpy as np

In [3]:
num = [1, 2, 3, 4]
ListOfList = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
# Array with rank one

numbers = np.array(num)
numbers

array([1, 2, 3, 4])

In [5]:
#Array with rank two

N1 = np.array(ListOfList)
N1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# np.arange (start, stop, step, dtype)
np.arange(0, 10, dtype = int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros((2, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
np.ones((6, 9), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
# np.linspace(start, stop, num, dtype) - returns evenly spaced number ove specified interval.
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.random.rand(2, 3)

array([[0.1938346 , 0.34439369, 0.65217255],
       [0.90459695, 0.3642126 , 0.12138989]])

In [13]:
np.random.randn(2, 3)

array([[-0.33221989, -0.9227961 , -1.16289177],
       [-0.5449807 ,  1.46500556,  0.76727931]])

In [14]:
RandomNumbers = np.random.randint(0, 50, 25)
RandomNumbers

array([44, 20, 39, 12, 20, 12, 12,  8,  9, 36,  3,  6,  2, 37,  4,  3, 14,
       22,  8, 23, 13, 32, 32, 15, 46])

In [15]:
RandomNumbers = RandomNumbers.reshape(5, 5)
RandomNumbers

array([[44, 20, 39, 12, 20],
       [12, 12,  8,  9, 36],
       [ 3,  6,  2, 37,  4],
       [ 3, 14, 22,  8, 23],
       [13, 32, 32, 15, 46]])

In [16]:
RandomNumbers.max()


46

In [17]:
RandomNumbers.min()

2

In [18]:
RandomNumbers.argmax()

24

In [19]:
RandomNumbers.argmin()

12

In [20]:
RandomNumbers.shape

(5, 5)

In [21]:
NewList = np.arange(0, 8, dtype = int).reshape(4, 2)
NewList

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
#3D array

NewList1 = np.arange(0, 8, dtype = int).reshape(2, 2, 2)
NewList1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
NewList1 = np.arange(0, 8, dtype = float).reshape(4, 1, 2)
NewList1

array([[[0., 1.]],

       [[2., 3.]],

       [[4., 5.]],

       [[6., 7.]]])

In [24]:
NewList1.dtype

dtype('float64')

In [25]:
Numbs = np.arange(0, 11)
Numbs

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
Numbs[4 : 8]

array([4, 5, 6, 7])

In [27]:
Numbs[4 : 8] = 100
Numbs

array([  0,   1,   2,   3, 100, 100, 100, 100,   8,   9,  10])

In [28]:
Numbs1 = Numbs.copy()
Numbs1

array([  0,   1,   2,   3, 100, 100, 100, 100,   8,   9,  10])

In [6]:
darray = np.random.randint(1, 100, 9).reshape(3, 3)
darray

array([[53, 49, 79],
       [43, 68, 54],
       [ 9, 89, 49]])

In [9]:
darray[1, 1]

68

In [11]:
darray[1][1]

68

In [14]:
ddarray = np.random.randint(1, 100, 25).reshape(5, 5)
ddarray

array([[38, 20, 67, 33, 11],
       [99, 12, 79, 89, 67],
       [29, 18, 11,  7, 86],
       [32, 16, 36, 33, 89],
       [39, 45, 54, 92, 56]])

In [24]:
ddarray[1:3, 1:3]

array([[12, 79],
       [18, 11]])

In [29]:
ddarray[2:5, 3:5]

array([[ 7, 86],
       [33, 89],
       [92, 56]])

In [32]:
ddarray[2:4, :4]

array([[29, 18, 11,  7],
       [32, 16, 36, 33]])

In [35]:
a = np.arange(0, 10, dtype=int)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = np.arange(0, 10, dtype=int)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a + b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
a - b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
a * b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [46]:
a / b

<ipython-input-46-d8e10abd5ab6>:1: RuntimeWarning: invalid value encountered in divide
  a / b


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [47]:
a // b

<ipython-input-47-d081371454f6>:1: RuntimeWarning: divide by zero encountered in floor_divide
  a // b


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [48]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [49]:
np.exp(b)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [50]:
np.sin(b)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [51]:
np.cos(b)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [52]:
np.tan(b)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [53]:
np.log(b)

<ipython-input-53-3f8f764f67ee>:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [54]:
a.sum()

45

In [55]:
a.max()

9

In [56]:
a.min()

0

In [58]:
a.mean()

4.5

In [57]:
a.var()

8.25

In [61]:
a.std()

2.8722813232690143

In [63]:
c = np.random.randint(1, 100, 9).reshape(3, 3)
c

array([[95, 60, 73],
       [65, 49,  9],
       [29, 33, 96]])

In [65]:
c.sum(axis = 0)

array([189, 142, 178])

In [66]:
c.sum(axis = 1)

array([228, 123, 158])

AxisError: axis 2 is out of bounds for array of dimension 2